# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nzcount <- function(x) {
    .Call('_taro_nzcount', PACKAGE = 'taro', x)
}

wpow <- function(x, gamma0) {
    .Call('_taro_wpow', PACKAGE = 'taro', x, gamma0)
}

sym_inv <- function(x) {
    .Call('_taro_sym_inv', PACKAGE = 'taro', x)
}

softThres <- function(x, lambda) {
    .Call('_taro_softThres', PACKAGE = 'taro', x, lambda)
}

scadThres <- function(z, lambda, k) {
    .Call('_taro_scadThres', PACKAGE = 'taro', z, lambda, k)
}

mySdiff <- function(x, y) {
    .Call('_taro_mySdiff', PACKAGE = 'taro', x, y)
}

bregpcdenet_Rcpp <- function(XY, XX, A, B, Lambda1, Lambda2, Mu, Nu, Beta0, method, control) {
    .Call('_taro_bregpcdenet_Rcpp', PACKAGE = 'taro', XY, XX, A, B, Lambda1, Lambda2, Mu, Nu, Beta0, method, control)
}

bregpcdenetdiag_Rcpp <- function(XY, XX, A, B, Lambda1, Lambda2, Mu, Nu, Beta0, method, control) {
    .Call('_taro_bregpcdenetdiag_Rcpp', PACKAGE = 'taro', XY, XX, A, B, Lambda1, Lambda2, Mu, Nu, Beta0, method, control)
}

get_cube_prod <- function(b, c, naind) {
    .Call('_taro_get_cube_prod', PACKAGE = 'taro', b, c, naind)
}

get_cube_prod_inv <- function(b, c, naind) {
    .Call('_taro_get_cube_prod_inv', PACKAGE = 'taro', b, c, naind)
}

taro_cpp_ur <- function(Y, X0, Ac, Bc, nlam, cindex, initw, Dini, Zini, Uini, Vini, ortV, Bv, control, misind, pl_method, naind, lamMat) {
    .Call('_taro_taro_cpp_ur', PACKAGE = 'taro', Y, X0, Ac, Bc, nlam, cindex, initw, Dini, Zini, Uini, Vini, ortV, Bv, control, misind, pl_method, naind, lamMat)
}

tarorrr_cpp_ur <- function(Y, X0, cindex, Ac, Bc, Zini, Cini, control) {
    .Call('_taro_tarorrr_cpp_ur', PACKAGE = 'taro', Y, X0, cindex, Ac, Bc, Zini, Cini, control)
}

tarorrr_cpp_ur2 <- function(Y, X0, cindex, Ac, Bc, Zini, Cini, control) {
    .Call('_taro_tarorrr_cpp_ur2', PACKAGE = 'taro', Y, X0, cindex, Ac, Bc, Zini, Cini, control)
}

tarorrr <- function(Y, X0, rank, cindex, Ac, Bc, Zini, control) {
    .Call('_taro_tarorrr', PACKAGE = 'taro', Y, X0, rank, cindex, Ac, Bc, Zini, control)
}

